[tool.pytest.ini_options]
pythonpath = [
  ".", "src",
]

markers = [
    "token: тесты для проверки токена в header запроса",
    "user: тесты для проверки вывода данных о пользователе",
    "tweet: тесты для проверки создания, вывода и удаления твитов",
    "like: тесты для проверки создания и удаления лайков",
    "follower: тесты для проверки создания и удаления подписок между пользователями",
    "image: тесты для проверки загрузки изображений к твитам",
]


filterwarnings = [
    "ignore::DeprecationWarning",
]

asyncio_mode="auto"
